########################################################################################
#+------------------------------------------------------------------------------------+#
#|                                                                                    |#
#|                               ShadowPerms Configuration                            |#
#|                                    By: dmulloy2                                    |#
#|                                                                                    |#
#+------------------------------------------------------------------------------------+#
########################################################################################

# This is the main configuration file for ShadowPerms
# It follows standard YAML procedure
# If there is an error on startup, make sure the config matches up with this:
# https://github.com/dmulloy2/ShadowPerms/blob/master/src/main/resources/config.yml
# Input: boolean - true/false, String - "text", integer - number

##############################################
#+------------------------------------------+#
#|           Global Configuration           |#
#+------------------------------------------+#
##############################################

# Auto Save - how often data files are saved (in minutes)
# enabled - boolean
# interval - integer
autoSave:
  enabled: true
  interval: 15

# Whether or not to allow command blocks to execute
# SwornPermission commands. Use at your own risk.
# input - boolean
allowCommandBlocks: false

# Debug
# input - boolean
debug: false

# Whether or not to force permission updates
# worldChange - when a player changes worlds
forceUpdate:
  worldChange: false

##############################################
#+------------------------------------------+#
#|                 Mirrors                  |#
#+------------------------------------------+#
##############################################

# Mirrors
# If '%main_world' is an element, it will automatically be
# parsed as the server's main world
# If '*' is an element, per-world files are disabled,
# defaulting to the parent world's files.
# If '%undefined_worlds' is an element, all unlisted worlds
# will be default to the parent world.

# User Mirrors
userMirrors:
  "%main_world":
    - "*"

# Group Mirrors
groupMirrors:
  "%main_world":
    - "*"

# Whether or not to have a unified set of users
# This is required with Bungee setups thru SQL
# YAML storage will use the main world
unifiedUsers: true

##############################################
#+------------------------------------------+#
#|                  Chat                    |#
#+------------------------------------------+#
##############################################

# Format Chat
# Whether or not to format chat with SwornChat
# input - boolean
formatChat: true

# Chat Format
# Accepted variables:
# {prefix} - the chatting player's prefix
# {name} - the chatting player's name
# {suffix} - the chatting player's suffix
# {message} - the chat message
# input - string
chatFormat: '{prefix}{name}{suffix}: {message}'

# Settings for /prefix and /suffix
# maxLength (int) - Maximum length
# forceReset (boolean) - Whether or not to force an '&r' after the prefix or suffix
# forceSpace (boolean) - Whether or not to force a space before or after, respectively

prefix:
  maxLength: 10
  forceReset: true
  forceSpace: false

suffix:
  maxLength: 10
  forceReset: true
  forceSpace: false

# Whether or not to use SwornChat to set a player's display name
setDisplay: true

##############################################
#+------------------------------------------+#
#|                AntiItem                  |#
#+------------------------------------------+#
##############################################

# Anti Item
# enabled (boolean) - Whether or not to enable AntiItem item management
# regulateEnchantments (boolean) - Disallow items with enchantments too high or low
# maxEnchantmentLevel (int) - Max enchantment level for enchantment regulation
antiItem:
  enabled: false
  regulateEnchantments: false
  maxEnchantmentLevel: 25

##############################################
#+------------------------------------------+#
#|                Database                  |#
#+------------------------------------------+#
##############################################

# YAML, MySQL, and SQLite are supported for users
# Only YAML is currently supported for groups

# YAML is the default, MySQL requires more information

database:
  userType: "YAML"
  groupType: "YAML"
  MySQL:
    url: "url:port"
    database: "swornperms"
    username: "user"
    password: "pass"
  