name: ShadowPerms
main: net.dmulloy2.shadowperms.ShadowPerms
version: ${project.version}${project.build.number}
author: dmulloy2
description: Comprehensive permission, chat, and world management system.
softdepend: [Vault]
load: POSTWORLD
commands:
  shadowperms:
    description: ShadowPerms root command
    usage: /<command> <args>
    aliases: [perms, perm]
  nick:
    description: Set a player's nickname
    usage: /<command> [player] <nick>
  prefix:
    description: Sets your prefix
    usage: /<command> <prefix>
    aliases: [pre]
  prefixreset:
    description: Reset a player's prefix
    usage: /<command> [player]
    aliases: [prer]
  realname:
    description: Get a player's real name
    usage: /<command> <player>
  suffix:
    description: Sets your suffix
    usage: /<command> <suffix>
    aliases: [suf]
  suffixreset:
    description: Reset a player's suffix
    usage: /<command> [player]
    aliases: [sufr]
permissions:
  shadowperms.admin:
    description: Full access to ShadowPerms commands
    default: op
    children:
      shadowperms.manage.users: true
      shadowperms.manage.groups: true
      shadowperms.chat.color: true
      shadowperms.chat.formatting: true
      shadowperms.chat.rainbow: true
      shadowperms.cmd.prefix: true
      shadowperms.cmd.reload: true
      shadowperms.cmd.save: true
      shadowperms.cmd.suffix: true
      shadowperms.cmd.nick: true
      shadowperms.cmd.realname: true
      shadowperms.moderator: true
  shadowperms.moderator:
    description: Allows access to commands meant for mods
    default: false
    children:
      shadowperms.cmd.prefix.reset: true
      shadowperms.cmd.prefix.reset.others: true
      shadowperms.cmd.suffix.reset: true
      shadowperms.cmd.suffix.reset.others: true
  shadowperms.manage.users:
    description: Manage users' permissions
    default: false
    children:
      shadowperms.user.view.info: true
      shadowperms.user.add.subgroup: true
      shadowperms.user.add.permission: true
      shadowperms.user.remove.subgroup: true
      shadowperms.user.remove.permission: true
      shadowperms.user.set.group: true
      shadowperms.user.set.prefix: true
      shadowperms.user.set.suffix: true
      shadowperms.user.set.option: true
      shadowperms.user.has.permission: true
      shadowperms.user.has.group: true
      shadowperms.user.has.option: true
      shadowperms.user.list.permissions: true
      shadowperms.user.reset: true
  shadowperms.user.view.info:
    default: false
  shadowperms.user.add.subgroup:
    default: false
  shadowperms.user.add.permission:
    default: false
  shadowperms.user.remove.subgroup:
    default: false
  shadowperms.user.remove.permission:
    default: false
  shadowperms.user.set.group:
    default: false
  shadowperms.user.set.prefix:
    default: false
  shadowperms.user.set.suffix:
    default: false
  shadowperms.user.set.option:
    default: false
  shadowperms.user.has.permission:
    default: false
  shadowperms.user.has.group:
    default: false
  shadowperms.user.has.option:
    default: false
  shadowperms.user.list.permissions:
    default: false
  shadowperms.user.reset:
    default: false
  shadowperms.manage.groups:
    description: Manage groups' permissions
    default: false
    children:
      shadowperms.group.view.info: true
      shadowperms.group.add.permission: true
      shadowperms.group.remove.permission: true
      shadowperms.group.set.prefix: true
      shadowperms.group.set.suffix: true
      shadowperms.group.set.option: true
      shadowperms.group.has.permission: true
      shadowperms.group.has.option: true
      shadowperms.group.list.permissions: true
      shadowperms.group.list.users: true
      shadowperms.group.list: true
      shadowperms.group.create: true
  shadowperms.group.view.info:
    default: false
  shadowperms.group.add.permission:
    default: false
  shadowperms.group.remove.permission:
    default: false
  shadowperms.group.set.prefix:
    default: false
  shadowperms.group.set.suffix:
    default: false
  shadowperms.group.set.option:
    default: false
  shadowperms.group.has.permission:
    default: false
  shadowperms.group.has.option:
    default: false
  shadowperms.group.list.users:
    default: false
  shadowperms.group.list.permissions:
    default: false
  shadowperms.group.list:
    default: false
  shadowperms.group.create:
    default: false
  shadowperms.chat.color:
    default: false
  shadowperms.chat.formatting:
    default: false
  shadowperms.chat.rainbow:
    default: false
  # Prefixes & Suffixes
  shadowperms.cmd.prefix:
    default: false
  shadowperms.cmd.prefix.reset:
    default: false
  shadowperms.cmd.prefix.reset.others:
    default: false
  shadowperms.cmd.suffix:
    default: false
  shadowperms.cmd.suffix.reset:
    default: false
  shadowperms.cmd.suffix.reset.others:
    default: false
  # Other Commands
  shadowperms.cmd.backup:
    default: false
  shadowperms.cmd.cleanup:
    default: false
  shadowperms.cmd.nick:
    default: false
  shadowperms.cmd.prune:
    default: false
  shadowperms.cmd.realname:
    default: false
  shadowperms.cmd.reload:
    default: false
  shadowperms.cmd.save:
    default: false
  shadowperms.cmd.version:
    default: true